  @ECHO OFF
  :KURULUMMODUSEC
  CLS
  ECHO.
  ECHO.
  ECHO.
  ECHO LUTFEN SECINIZ (1, 2 VEYA 3) :
  ECHO.
  ECHO #########################################################################
  ECHO.
  ECHO.
  ECHO    1 - EGLENCE OYUNU (FULL OYUN + MULTIPLAYER)
  ECHO.
  ECHO    2 - HIKAYE MODU   (ILERLEME KAYDEDILEBILIR)
  ECHO.
  ECHO    3 - ONLINE MULTIPLAYER
  ECHO.
  ECHO.
  ECHO #########################################################################
  ECHO.
  SET KURULUMMODU=ERR
  SET /P KURULUMMODU=LUTFEN LISANS KODUNUZU GIRINIZ :
  IF NOT %UOA%==UOA EXIT
  IF %KURULUMMODU%==MİRAC ECHO KOD HATALI & GOTO :KODHATA
  IF %KURULUMMODU%==1071 ECHO OYUN MODU 1071 & GOTO :EGLENCE
  IF %KURULUMMODU%==1453 ECHO OYUN MODU 1453 & GOTO :HIKAYE
  IF %KURULUMMODU%==3 ECHO OYUN MODU 3 & GOTO :MULTIMULTI
  IF %KURULUMMODU%==ERR GOTO :KURULUMMODUSEC

  :KODHATA
echo KODHATA
pause
GOTO :KURULUMMODUSEC


  :EGLENCE
echo eglence
pause > NULL
  
  :HIKAYE
echo hikaye
pause
  
  
  :MULTIMULTI
echo MULTIMU
pause
